import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/responsive.css";
import Navbar from "@/components/shared/Navbar";
import FooterCTA from "@/components/shared/FooterCTA";
import Footer from "@/components/shared/Footer";

/** Pairs with `--font-body` / `--font-heading` used throughout `globals.css`. */
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "ODOP New Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body>
        <Navbar />
        {children}
        {/* <FooterCTA/> */}
        <Footer />
      </body>
    </html>
  );
}
